"""
Static preprocessing resources.
"""

EMOJI_MAP = {
    "😂": " [LAUGH] ",
    "🤣": " [LAUGH] ",
    "😡": " [ANGRY] ",
    "🤬": " [ANGRY] ",
    "😠": " [ANGRY] ",
    "❤️": " [LOVE] ",
    "❤": " [LOVE] ",
    "😍": " [LOVE] ",
    "😭": " [CRY] ",
    "😢": " [CRY] ",
}

ABUSE_LEXICON = {
    "loser": "[ABUSIVE]",
    "idiot": "[ABUSIVE]",
    "stupid": "[ABUSIVE]",
    "useless": "[ABUSIVE]",
    "cheap": "[ABUSIVE]",
    "clown": "[ABUSIVE]",
    "chutiya": "[ABUSIVE]",
    "bewakoof": "[ABUSIVE]",
    "pagal": "[ABUSIVE]",
    "madarchod": "[ABUSIVE]",
    "mc": "[ABUSIVE]",
    "behenchod": "[ABUSIVE]",
    "bc": "[ABUSIVE]",
    "asshole": "[ABUSIVE]",
    "pathetic": "[ABUSIVE]",
    "trash": "[ABUSIVE]",
    "gadhe": "[ABUSIVE]",
    "aukaat": "[ABUSIVE]",
    "ghatiya": "[ABUSIVE]",
    "bitch": "[ABUSIVE]",
    "bakwas": "[ABUSIVE]",
    "dumb": "[ABUSIVE]",
    "dumbass": "[ABUSIVE]",
    "ugly": "[ABUSIVE]",
    "fat": "[ABUSIVE]",
    "slut": "[ABUSIVE]",
    "whore": "[ABUSIVE]",
    "bastard": "[ABUSIVE]",
    "fuck": "[ABUSIVE]",
    "shit": "[ABUSIVE]",
    "garbage": "[ABUSIVE]",
    "kutta": "[ABUSIVE]",
    "kutte": "[ABUSIVE]",
    "kamina": "[ABUSIVE]",
    "harami": "[ABUSIVE]",
    "bsdk": "[ABUSIVE]",
    "randi": "[ABUSIVE]",
    "suar": "[ABUSIVE]",
    "tatti": "[ABUSIVE]",
    "nalla": "[ABUSIVE]",
    "hoe": "[ABUSIVE]",
    "hoes": "[ABUSIVE]",
    "pussy": "[ABUSIVE]",
    "ass": "[ABUSIVE]",
    "nigga": "[ABUSIVE]",
    "niggas": "[ABUSIVE]",
    "kill": "[ABUSIVE]",
    "die": "[ABUSIVE]",
    "murder": "[ABUSIVE]",
    "mar": "[ABUSIVE]",
}

OBFUSCATION_PATTERNS = {
    r"b[\W_]*i[\W_]*t[\W_]*c[\W_]*h": "bitch",
    r"i[\W_]*d[\W_]*i[\W_]*o[\W_]*t": "idiot",
    r"l[\W_]*o[\W_]*s[\W_]*e[\W_]*r": "loser",
    r"c[\W_]*l[\W_]*o[\W_]*w[\W_]*n": "clown",
    r"a[\W_]*s[\W_]*s[\W_]*h[\W_]*o[\W_]*l[\W_]*e": "asshole",
    r"f[\W_]*u[\W_]*c[\W_]*k": "fuck",
    r"s[\W_]*h[\W_]*i[\W_]*t": "shit",
    r"d[\W_]*u[\W_]*m[\W_]*b": "dumb",
    r"s[\W_]*l[\W_]*u[\W_]*t": "slut",
    r"w[\W_]*h[\W_]*o[\W_]*r[\W_]*e": "whore",
    r"k[\W_]*u[\W_]*t[\W_]*t[\W_]*a": "kutta",
    r"h[\W_]*a[\W_]*r[\W_]*a[\W_]*m[\W_]*i": "harami",
    r"r[\W_]*a[\W_]*n[\W_]*d[\W_]*i": "randi",
    r"s[\W_]*u[\W_]*a[\W_]*r": "suar",
    r"c[\W_]*h[\W_]*u[\W_]*t[\W_]*i[\W_]*y[\W_]*a": "chutiya",
    r"p[\W_]*u[\W_]*s[\W_]*s[\W_]*y": "pussy",
    r"n[\W_]*i[\W_]*g[\W_]*g[\W_]*a": "nigga",
}

TOKEN_CATEGORIES = {
    "kill": "Threat / Violence",
    "die": "Threat / Violence",
    "murder": "Threat / Violence",
    "mar": "Threat / Violence",
    "fuck": "Profanity",
    "shit": "Profanity",
    "bitch": "Profanity",
    "ass": "Profanity",
    "pussy": "Profanity",
    "hoe": "Profanity",
    "hoes": "Profanity",
    "asshole": "Profanity",
    "chutiya": "Profanity",
    "madarchod": "Profanity",
    "mc": "Profanity",
    "behenchod": "Profanity",
    "bc": "Profanity",
    "randi": "Profanity",
    "loser": "Harassment / Insult",
    "idiot": "Harassment / Insult",
    "stupid": "Harassment / Insult",
    "useless": "Harassment / Insult",
    "cheap": "Harassment / Insult",
    "clown": "Harassment / Insult",
    "bewakoof": "Harassment / Insult",
    "pagal": "Harassment / Insult",
    "gadhe": "Harassment / Insult",
    "aukaat": "Harassment / Insult",
    "ghatiya": "Harassment / Insult",
    "bakwas": "Harassment / Insult",
    "dumb": "Harassment / Insult",
    "dumbass": "Harassment / Insult",
    "ugly": "Harassment / Insult",
    "fat": "Harassment / Insult",
    "slut": "Harassment / Insult",
    "whore": "Harassment / Insult",
    "bastard": "Harassment / Insult",
    "garbage": "Harassment / Insult",
    "kutta": "Harassment / Insult",
    "kutte": "Harassment / Insult",
    "kamina": "Harassment / Insult",
    "harami": "Harassment / Insult",
    "bsdk": "Harassment / Insult",
    "suar": "Harassment / Insult",
    "tatti": "Harassment / Insult",
    "nalla": "Harassment / Insult",
    "pathetic": "Harassment / Insult",
    "trash": "Harassment / Insult",
    "nigga": "Hate Speech",
    "niggas": "Hate Speech",
}

